### ISSUE TITLE
Figure out a way to proactively update configs using deprecated features

### ISSUE THREAD

**Issue by csomh** [packit/research#159]
In many cases transforming deprecated config options (like `synced_files` or `metadata`) into the current format can be done programmatically, so we could come up with a way to propose these updates as PRs to the projects still using them. This could speed up their deprecation and let us remove some code sooner.

Research how this could be done.

One of the things that needs to be done is to get an up-to-date version of all the packit.yaml-s currently in use. We discussed either saving them in the DB, or writing a script to get the list of projects and branches using the service API, and downloading the configs.

**Comment by lachmanfrantisek** [comment]
ping the sync
