### ISSUE TITLE
Research architecture of console.redhat.com

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/research#178]
The goal of this task is to have a clear understanding of what is needed to incorporate Packit into console.redhat.com ( #175). Specifically:

* [x] What is the architecture?
  * [x] How are services connected to each other?
  * [x] How do services communicate?
* [x] How are the services deployed?
* [x] What are the formal/technical requirements?
* [x] Gather the information above and present the finding to the team.
  * [x] Show the team example of the existing service.

You can also meet people behind the console and/or developers of other services to get the information.

----
*This issue is part of the #175 epic.*

**Comment by TomasTomecek** [comment]
I suggest reaching out to the image builder team: Ondrej, Tomas or Sanne.
