### ISSUE TITLE
Desing the OpenScanHub service integration

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/research#213]
Design the work needed to be done to provide OpenScanHub scans for the users of service.

The scanning possibility is already present in Packit Python API and CLI. (https://github.com/packit/packit/pull/2301)

Original idea of the prototype:
* Don't do this as a separate job type (at least for the start).
* Run this by default (and have config to disable this) after every successful Copr build when there is a build for the PR-target branch available (=>to provide differential scan).
* Reporting can be done later -- for now, we can just provide a user an OpenScanHub job URL to watch the progress.
  * Either on the CheckResult and/or dashboard result page. Or, create a separate status.

TODO:
* [ ] Check if the idea is implementable. Suggest and discuss changes/enhancements with the team.
* [ ] Prepare tasks for the real implementation.

**Comment by lbarcziova** [comment]
Created packit/packit-service#2454
